#!/usr/bin/env python3
"""
This module contains an asynchronous coroutine that collects 10 random numbers.
"""

import asyncio
from typing import List
from 0_async_generator import async_generator


async def async_comprehension() -> List[float]:
    """
    Coroutine that collects 10 random numbers from async_generator using
    asynchronous comprehension and returns them.

    Returns:
        A list of 10 random floats generated by async_generator.
    """
    return [num async for num in async_generator()]
